export const URLS = {
  businessforContractorById:
    "Business/businessfor-contractorby-id?idUser={idUser}&userType={userType}",
  documents: "/documentmonitor/all-documents",
  deleteDocuments: (id: string) =>
    `/documentmonitor/delete-document?monitorDocumentId=${id}`,
  documentType: "/documentmonitor/document-type",
  addDocument: "/documentmonitor/create-document",
  updateDocument: "/documentmonitor/update-document",
  refreshToken: "/account/refresh-token",
  changePassword: "/user/change-password",
  businessInfo: "business/business-info",
  login: "account/login",
  businessScheme: "scheme/business",
  schemeRowData: "business/application-rowdata-schemewise",
  applicationStatusandAnswer: "application/application-status-andanswer",
  businessList: "/posts",
  createAnswer: "application/create-answer",
  submitApplication: "application/submit-application",
  switchBusiness: "business/switch-buiness?bid={bid}",
  getAndPostProfile: "user/profile",
  register: "account/register-user",
  bundleRegisterData: "master/bundle-registration-data",
  profile: "user/profile",
  searchAddress: "Webservice/GetPostcodeAddressDetails",
  sendMail: "account/send-mail",
  verifyEmail: "account/verify-registration",
  forgotPassword: "account/forgot-password",
  uploadsFiles: "application/UploadFiles",
  updateUserInfo: "device/device-info",
  emailExists: "account/checkduplicate-phoneandemail",
  sendSms: "account/send-sms",
  deleteUser: "account/delete-user",
  downloadBundle: (id: string) => `/ota/download/${id}`,
  checkVersion: '/ota/check',
};
